### ISSUE TITLE
[解決]: トークのバックアップを自動保存可能にする

### ISSUE THREAD

**Issue by atuy1219** [areteruhiro/LIME-beta-hiro#10]
### 提案内容

トークのバックアップを自動保存できるようにする

**Comment by areteruhiro** [comment]
自動保存の意義って何かあるんですか？
バックアップせずに消しちゃったみたいな感じですか？

**Comment by atuy1219** [comment]
ただ毎日100MBクラスのファイルが保存されるのはちょっときついので自動でバックアップをするのは naver_line_backup.db （日付等が名前に含まれていないやつ）のみとかにしてもらえると助かります

**Comment by areteruhiro** [comment]
了解です。
時間がある時対応しますね。
そのような使い方があったんですね

**Comment by areteruhiro** [comment]
このような、形になるかわかりませんが、

Taskerはウィジェットの実行という、アクションはありますか？

lime側でウィジェットを作成するというのもありだなと思いまして

**Comment by atuy1219** [comment]
ないですねー
Taskerのウィジェットから既存のタスクを実行はできますが、他のアプリのウィジェットを実行てのはなさそうです

**Comment by areteruhiro** [comment]
バックアップ自体は比較的簡単な処理なのですがトリガーをどうするかという問題がありますね。

**Comment by atuy1219** [comment]
ちょっとAndroid開発に詳しくないのでできるのか分かりませんがTaskerでIntentを送信できるんですけど、それでバックアップ取れませんかね…

**Comment by areteruhiro** [comment]
アイデアありがとうございます、多分できました！

**Comment by atuy1219** [comment]
Taskerでもいけました！
ありがとうございます！
![Screenshot_20241101-222734](https://github.com/user-attachments/assets/a840a1f5-9e5d-4b7b-a9fe-83836e1cd7e1)
（なぜか右端が見切れてしまった…）

上の投稿のクラスをコピーしたら最後に ` が付いてたので消しといたほうがいいかもです…！

**Comment by areteruhiro** [comment]
> Taskerでもいけました！
> ありがとうございます！
> ![Screenshot_20241101-222734](https://github.com/user-attachments/assets/a840a1f5-9e5d-4b7b-a9fe-83836e1cd7e1)
> （なぜか右端が見切れてしまった…）
> 
> 上の投稿のクラスをコピーしたら最後に ` が付いてたので消しといたほうがいいかもです…！

画像提供ありがとうございます。

` 消しておきました

**Comment by atuy1219** [comment]
これバックアップがnaver_line_backup.dbじゃない、日付等が付いてるほうになってますが、付いてないほうに変えることってできます？

あと、できれば画像のバックアップも自動でできたら嬉しいです

**Comment by areteruhiro** [comment]
すみません、意図せず勝手に編集してしまいました。
→
了解です。
次のアプデでそうしておきます。

**Comment by areteruhiro** [comment]
リリースしました

**Comment by atuy1219** [comment]
ありがとうございます！

**Comment by areteruhiro** [comment]
Tasker詳しくないのでよければreadに手順記載してもらうことってできますか？

**Comment by areteruhiro** [comment]
"トーク履歴のバックアップを開始"
"トーク画像フォルダのバックアップを開始"
"バックアップを開始"
これがトリガーです
