### ISSUE TITLE
[質問・ReadMeの修正案]: 分割apkで動作するか否か

### ISSUE THREAD

**Issue by KoB887** [areteruhiro/LIME-beta-hiro#22]
### 提案内容

Pixel 8a (Android15)
KernelSU 11986 + LSPosed 1.10.1(7115) 
LIMEs 1.14.2d + LINE 14.19.1で使用しています。日々の開発本当にありがとうございます。

本題ですが、本家のreadmeにはインストール手順の記載があり、最初に分割APKを使用しないよう指定されています。
こちらには記載がありませんが、XAPKインストールでも動作するのでしょうか？

こちらで試してみたところ、広告削除やボトムバーの変更は適用されましたが、通知者の確認や未読のまま閲覧する機能は動いていないようにみえました。
試してみただけなのでログ等の保存ができていないのが申し訳ないのですが…。

もしAPKでのインストールが必須であればその旨Readmeに記載することを提案します。

**Comment by areteruhiro** [comment]
どのxapkで、されたか教えてください
試します

**Comment by KoB887** [comment]
最初に気づいたのはapkcomboからダウンロードしたものを使用していたときでした。
未読のまま閲覧スイッチがタッチで反応せず、しかし広告は非表示であったので気にせず使っていました。
申し訳ないのですがログを保存していなかったです…。

現在apkpureからのxapkをSAIでインストールして使用していますが、通知の遅れもなく動作に問題はありません。
ログは
　Loading legacy module io.github.hiro.lime　…
くらいで明らかなエラーログはなさそうですね。

**Comment by areteruhiro** [comment]
> 最初に気づいたのはapkcomboからダウンロードしたものを使用していたときでした。
> 未読のまま閲覧スイッチがタッチで反応せず、しかし広告は非表示であったので気にせず使っていました。
> 申し訳ないのですがログを保存していなかったです…。
> 
> 現在apkpureからのxapkをSAIでインストールして使用していますが、通知の遅れもなく動作に問題はありません。
> ログは
> 　Loading legacy module io.github.hiro.lime　…
> くらいで明らかなエラーログはなさそうですね。

バイト終わったら確認しますね

**Comment by areteruhiro** [comment]
未読のまま閲覧する機能はブラックテーマだとわかりにくいですが、緑色になったらオンの状態です。
既読者確認については、注意事項は特にないですね、、以下にファイルは作成されていますか？

**Comment by areteruhiro** [comment]
機能します
