### ISSUE TITLE
【報告,やり方】:再インストール時のトークのリストアの方法

### ISSUE THREAD

**Issue by harutoku** [areteruhiro/LIME-beta-hiro#5]
### LSPatch 使用の有無

- [X] 私は LSPatch を使用している状態での報告を行います

### 内容の詳細

LIME-beta-hero v1.10.17，LINE v14.16.0 の環境において、バックアップしたトークのリストアが行えない
“リストア中にエラーが発生しました”とのメッセージが表示される
バックアップ自体は成功した旨のメッセージが表示され、実際に“LimeBackup”フォルダが作成されていた

### 再現する手順

1）LIME-beta-hero v1.10.17，LINE v14.16.0 の環境において、“LIMEs”ボタンを押し、“バックアップ”ボタンを押す
2）アプリを1度アンインストールし、再度インストール、ログインする
ログイン時にgoogleアカウントでのログインはトークンのせい？で不可
3）“LIMEs”ボタンを押し、“リストア”ボタンを押す

### 有効にしている LIME の設定

VOOM アイコンを削除, ニュースまたは通話アイコンを削除, ボトムバーのアイコンを均等に配置, ボトムバーのアイコンのラベルを削除, 広告を削除, おすすめを削除, LYP プレミアムのおすすめを削除, 通知から "通知オフ" アクションを削除, WebView を規定のブラウザにリダイレクト, トラッキング通信をブロック, LINE バージョンの確認を停止

### バージョンの確認

- [X] 私は最新版の LIME を使用しており、それに適合するバージョンの LINE アプリを使用しています

**Comment by areteruhiro** [comment]
https://github.com/areteruhiro/LIME-beta-hiro/releases/tag/v1.10.3
仕様です。
上の下をお読みになってください。
readにかいていなくてすみません。

**Comment by areteruhiro** [comment]
復元したいファイルを移動させ、名前をnaver_line_backup.db　に変更し、ファイルをLimeBackup に移動させます、その際「入れ替える」機能を使うと、正常にリストアできると思います

**Comment by areteruhiro** [comment]
今、公式のコラボレータさんに、解決できないか試してもらってます。

**Comment by areteruhiro** [comment]
⇑でもできないでしょうか？

**Comment by areteruhiro** [comment]
①バックアップしたいファイルを移動させる
②LINEを開いてバックアップ
③移動させたファイルの名前を`naver_line_backup.db`に変更する
④LIME backup フォルダに入れ替え
で、移動させる
⑤リストアさせる

**Comment by harutoku** [comment]
失礼致しました、当該部分の記述を読めていませんでした
復元したいファイルを〜の部分がよくわからないのですが、“バックアップ”ボタンを押した時点で“LimeBackup”フォルダ内にバックアップファイルが作成されるわけではないのですか？
フォルダ内にある“naver_line_backup_20241021_234301.db”(私がバックアップした日付のファイル)がそれなのでしょうか、それの日付部分を削除せよということですか？

**Comment by areteruhiro** [comment]
naver_line_backup_20241021_234301.db
naver_line_backup.db を削除する（または、20241021_234301と同じものなら移動させる）
play.google.com/store/apps/details?id=me.zhanghai.android.files
で、LIME Back upの外に一度出します。 

lineを開いて、バックアップボタンをもう一度押します。

フォルダlime backupに
naver_line_backup が
作成されたと思います。

LIME Back upの外にある、naver_line_backup_20241021_234301の名前を、naver_line_backup.dbに変更させます。
その、
名前を変更した、naver_line_backup.dbを、lime backupの中に、移動（置き換え）ます。

**Comment by areteruhiro** [comment]
上のファイルの場合、「切り取り」を使ってください

**Comment by areteruhiro** [comment]
わからなさそうなら、動画とります。わかりましたか？

**Comment by harutoku** [comment]
ありがとうございます、やりかたはよくわかりました
ですが残念ながら当方の環境ではリストアは叶いませんでした
同様のエラーメッセージが出力されてしまいます
一応元々あった“naver_line_backup”ファイルもファイルサイズが同じだったため残してありますが
“LimeBackup”フォルダの中は新しくできた“naver_line_backup_日付”ファイル(以降日付ファイル)と、古い日付ファイルをnaver_line_backupに改名したもの、“chats_backup”フォルダの3つが存在する状態で間違いないでしょうか……

**Comment by areteruhiro** [comment]
https://youtu.be/94JN4NLGdOI

**Comment by areteruhiro** [comment]
どうかでの
Anaver_line_backupは、元々は日付が書かれていたファイルです。

**Comment by areteruhiro** [comment]
もし、この動画のようにしてできないならバックアップが、出来るかどうか試してもらっていいでしょうか。

お手数おかけいたします

**Comment by areteruhiro** [comment]
できない場合、いわゆる「置き換え」ができていない可能性があります。

**Comment by harutoku** [comment]
古い日付ファイルを“naver_line_backup”に改名して置き換えるのではなく、“naver_line_backup”ファイルを新しいものに交換するということですか？
その場合ですと、既に古いファイルを交換して上書きしてしまっているので不可能になってしまいました
私の認識が誤っていたようです
長々とお付き合いありがとうございました
次回以降正しい方法でバックアップしようと思います

**Comment by areteruhiro** [comment]
アンインストールする前に行った、バックアップした“naver_line_backup”ファイルがある場合は、新しいバックアップが正常に行えない(日付のついているnaver_line_backupファイルは作成されますが、naver_line_backupファイルは上書きされないはずです)
今の@harutoku さんの環境がわかりませんが、
リストアを押して
リストアが成功しました
は表示されますか？

何回も質問すみませんが

**Comment by areteruhiro** [comment]
改名して置き換えるはその通りです、
が置き換える前に、インストール後、バックアップを一度行い正常に行う必要があります。

私の日本語能力の問題ですか？

**Comment by areteruhiro** [comment]
基本的に、リストアが行えない＝バックアップも行えません
なので、動画上ではバックアップをするで確認しています

**Comment by areteruhiro** [comment]
リストアされるのは、日付のついていない
naver_line_backupファイル
です

**Comment by harutoku** [comment]
恐らく、バックアップを一度行う(確認)の手順を踏まないまま、置き換えしてしまっていたため、リストア出来ていませんでした

もう一度正しい手順を踏んでリストアを試してみたいのですが、ログインを連続でしすぎたのか、

・LINE側から“〇〇分経ってからログインしてください”系のメッセージが出だす

・recaptchaで人間かどうか確認される

などアカウントが心配になってくる雰囲気になって参りました
検証は時間を置いてからにさせてください、すいません

**Comment by areteruhiro** [comment]
検証はついでで大丈夫ですよ。

**Comment by harutoku** [comment]
ちなみに

バックアップボタンを押すと、“naver_line_backup”ファイルと日付ファイルが作成される
→“naver_line_backup”ファイルを他のディレクトリに移動させる
───再インストール後───
もう一度バックアップボタンを押す
同様にファイルが作成される
→移動させておいた“naver_line_backup”ファイルを戻して上書きする
というやり方でも問題ないでしょうか

**Comment by areteruhiro** [comment]
それでも問題ありません。

**Comment by harutoku** [comment]
本日5chスレッド内で協議されていた、通知の話も兼ねてバックアップとリストアを行ってみましたが、やはり私の環境では“リストア中にエラーが発生しました”のメッセージが出てしまいます

**Comment by areteruhiro** [comment]
お手数おかけしますが、画面録画していただいたものを見せていただけないでしょうか。
手順の確認を致します。
Twitterの https://twitter.com/areteruhiro
まで、おねがいします。

**Comment by harutoku** [comment]
承知致しました、画面録画というのは、私のファイル移動の手順を撮ればいいですか？

**Comment by areteruhiro** [comment]
https://youtu.be/94JN4NLGdOI
この動画のようにしてくれますか

**Comment by harutoku** [comment]
https://twitter.com/shumi423216
このアカウントです、フォローバックお願いします
