### ISSUE TITLE
[解決済み]: 最近更新されたプロフィールの非表示

### ISSUE THREAD

**Issue by Kdroidwin** [areteruhiro/LIME-beta-hiro#7]
### 提案内容

![652bc43e630ed16650552fbf765de09cd56800f7](https://github.com/user-attachments/assets/97606f6e-8555-4fbb-8ed1-ec310129a145)

https://guide.line.me/ja/account-and-settings/settings/hometab-update.html

**Comment by areteruhiro** [comment]
これについて、任意のものを自分で選択して、追加できるようにしてもいいかなと考えています。（バッテリー消費が懸念ですが）
どうしましょうか？

**Comment by Kdroidwin** [comment]
任意のものを自分で追加して、消すものを追加できるようにしてもいいと思います。

**Comment by areteruhiro** [comment]
これについて、有効にしてしまうと、友達リストの友達も削除されてしまうため、方法を検討中です
オプションだけ追加して、実際の機能は追加していません

**Comment by areteruhiro** [comment]
非表示と言うより、更新したという情報を受け付けないようにして実装しますね。

**Comment by Kdroidwin** [comment]
個人的にはそちらのほうが嬉しいですね。

**Comment by areteruhiro** [comment]
機能1.12.4aで追加しました
