### ISSUE TITLE
【bug】: 生体認証の連携が行えない

### ISSUE THREAD

**Issue by harutoku** [areteruhiro/LIME-beta-hiro#8]
### LSPatch 使用の有無

- [X] 私は LSPatch を使用している状態での報告を行います

### 内容の詳細

LIME-beta-hero v1.10.17，LINE v14.16.0 の環境において、生体認証の連携が行えない
“サーバーエラーが発生しました。
再度お試しください。”とのメッセージが表示される
以前当方が使用していた
LIME v1.8.1，LINE v14.3.2 の環境では、問題なく連携できていた

解決の意義としては、windows版LINEのログイン、“スマートフォンを使ってログイン”を可能にすることである
もう一つwindows版へのログイン方法として、QRコードをスマホ版で読み取る方法があるが、こちらの場合は頻繁にログアウトしてしまう

### 再現する手順

上記の環境を用意し、生体認証の連携を行う

### 有効にしている LIME の設定

VOOM アイコンを削除, ニュースまたは通話アイコンを削除, ボトムバーのアイコンを均等に配置, ボトムバーのアイコンのラベルを削除, 広告を削除, おすすめを削除, LYP プレミアムのおすすめを削除, 通知から "通知オフ" アクションを削除, WebView を規定のブラウザにリダイレクト, トラッキング通信をブロック, LINE バージョンの確認を停止

### バージョンの確認

- [X] 私は最新版の LIME を使用しており、それに適合するバージョンの LINE アプリを使用しています

**Comment by areteruhiro** [comment]
報告ありがとうございます。確認致します。

**Comment by harutoku** [comment]
やはりroot環境では発生しないのですね……

**Comment by areteruhiro** [comment]
認証系なので、一旦放置させてください。

**Comment by areteruhiro** [comment]
恐らく、通知が来ない問題と同じように
バージョンを引くので連動してからアップデートしたら連動できると思います。

**Comment by harutoku** [comment]
現状 v14.3.2から上書きアップデートしていますが、たしかに通知は届くようになりましたがこれは解決しませんでした

**Comment by areteruhiro** [comment]
低いバージョンで、連携してから
アップデートするという意味なのですが、
連携解除されますか？

**Comment by areteruhiro** [comment]
（自宅に帰ったら試すので、試さなくて大丈夫です）

**Comment by areteruhiro** [comment]
むりですね、、うーん、治せるのかなー。

**Comment by harutoku** [comment]
多分ぼくにしか需要がない機能なんで、他に皆さんから望まれてる機能があるならそっち優先で大丈夫です！いろいろありがとうございます！

**Comment by areteruhiro** [comment]
いや、この機能PC使う人にとったら必須なんですよね〜

**Comment by harutoku** [comment]
v1.11.3LsPatchを14.17.0へパッチで解決しました、いつもありがとうございます
